# Generated by Django 4.1.5 on 2023-04-11 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0004_vacancy_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='tags',
            field=models.ManyToManyField(blank=True, to='vacancies.tag'),
        ),
    ]
